### ISSUE TITLE
How to load a partial model after training is done?

### ISSUE THREAD

**Issue by trane293** [agis85/multimodal_brain_synthesis#3]
Hi!

I have another questions: Once a model is trained, say using 'T1', 'T2' as inputs, and 'T2FLAIR' as output, how can I extract the partial model with only 'T1' as input and 'T2FLAIR' as output?

I tried using the get_partial_model function in model.py, but it gives the following error:

```
/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/layers/core.py:640: UserWarning: `output_shape` argument not specified for layer lambda_6 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 16, 240, 240)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/layers/core.py:640: UserWarning: `output_shape` argument not specified for layer lambda_7 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 16, 240, 240)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
Traceback (most recent call last):
  File "/home/anmol/softwares/PyCharm-2018.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/anmol/softwares/PyCharm-2018.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/anmol/softwares/PyCharm-2018.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/anmol/projects/multimodal_brain_synthesis/model_testing.py", line 34, in <module>
    exp.load_partial_model(folder=model_path, model_name='model', input_modalities=['T1'], output_modality='T2FLAIR')
  File "/home/anmol/projects/multimodal_brain_synthesis/runner.py", line 45, in load_partial_model
    self.mm.model = self.mm.get_partial_model(input_modalities, output_modality)
  File "/home/anmol/projects/multimodal_brain_synthesis/model.py", line 305, in get_partial_model
    outputs += self.get_embedding_distance_outputs(embeddings)
  File "/home/anmol/projects/multimodal_brain_synthesis/model.py", line 123, in get_embedding_distance_outputs
    concat_emb = merge(all_emb_flattened, mode='concat', concat_axis=1, name='em_concat')
  File "/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/legacy/layers.py", line 455, in merge
    name=name)
  File "/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/legacy/layers.py", line 107, in __init__
    node_indices, tensor_indices)
  File "/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/legacy/layers.py", line 132, in _arguments_validation
    str(layers))
TypeError: A Merge should only be applied to a list of layers with at least 2 elements. Found: [<keras.layers.core.Lambda object at 0x7f90126b5450>]
```
To get around this problem, I commented out the ` outputs += self.get_embedding_distance_outputs(embeddings)
` line. 

This was I was able to successfully load the model for 'T1' input and 'T2FLAIR' output. However, this does not work for 'T2' input and 'T2FLAIR' output, and gives the following error:

```
/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[em_0_dec_..., inputs=[/enc_T2_i...)`
  '` call to the Keras 2 API: ' + signature)
Traceback (most recent call last):
  File "/home/anmol/softwares/PyCharm-2018.1/helpers/pydev/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<input>", line 1, in <module>
  File "/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/anmol/.virtualenvs/multimodal_synthesis/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1691, in __init__
    str(layers_with_complete_input))
RuntimeError: Graph disconnected: cannot obtain value for tensor /enc_T1_input at layer "enc_T1_input". The following previous layers were accessed without issue: []
```

Any help would be appreciated. 
Thanks!

**Comment by trane293** [comment]
I think I found a solution, but not sure if it's the intended use. The problem arises in the following code snippet: 

```python
if self.spatial_transformer:
        print 'Adding a spatial transformer layer'
        input_shape = (self.latent_dim, self.H, self.W)
        tpn = tpn_maker(input_shape)
        mod1 = ind_emb[0]
        aligned_ind_emb = [mod1]
        for mod in ind_emb[1:]:
            aligned_mod = merge([tpn([mod1, mod]), mod], mode=STMerge, output_shape=input_shape)
            aligned_ind_emb.append(aligned_mod)
        ind_emb = aligned_ind_emb
```
Let's assume the input modalities are: ['T1', 'T2']. The code defines a merge layer between 'T1' and a spatial transformation of 'T1' and 'T2', let's say ST_T1_T2. 

However in doing so, the final `ind_emb` does not retain the original  'T2' input. The contents of `ind_emb` should have been: ['T1', 'T2', 'ST_T1_T2'], however, the contents become: ['T1', 'ST_T1_T2']. Hence when I try to load a model with only 'T2' as input, it fails, because it cannot find the original 'T2' input. 

The fix is here:

```python
if self.spatial_transformer:
    print 'Adding a spatial transformer layer'
    input_shape = (self.latent_dim, self.H, self.W)
    tpn = tpn_maker(input_shape)
    aligned_ind_emb = ind_emb
    for mod in range(len(ind_emb)-1):
        aligned_mod = merge([tpn([ind_emb[mod], ind_emb[mod+1]]), ind_emb[mod+1]], mode=STMerge, output_shape=input_shape)
        aligned_ind_emb.append(aligned_mod)
    ind_emb = aligned_ind_emb
```

`ind_emb` now contains the following: ['T1',  'T2',  'ST_T1_T2']. If I try to load a model with only  'T2' input, I can successfully do it now. 

Please let me know if this is the intended use of Spatial Transformer. The paper doesn't describe the use to ST layer, so I'm in the dark. 

The fix code I provide will have a different behaviour when more than two inputs are given. For instance, for inputs: ['T1',  'T2', 'T1CE'], the `ind_emb` after spatial transformer is added, will be: ['T1', 'T2', 'T1CE', 'ST_T1_T2', 'ST_T2_T1CE']. Is this how  it's supposed to be?

**Comment by anlarro** [comment]
Hi, Did you manage to get this work for more that 2 inputs? I have input_modalities = ['T1', 'T2', 'FLAIR'] and can only get partial models for inputs ['T1','T2'] and ['T1','FLAIR']. For ['T2','FLAIR'] I get

"RuntimeError: Graph disconnected: cannot obtain value for tensor /enc_T1_input at layer "enc_T1_input". The following previous layers were accessed without issue: []"

I have tried your solution but I get: "Output "em_4_dec_T1" missing from loss dictionary"

**Comment by anlarro** [comment]
> I think I found a solution, but not sure if it's the intended use. The problem arises in the following code snippet:
> 
> ```python
> if self.spatial_transformer:
>         print 'Adding a spatial transformer layer'
>         input_shape = (self.latent_dim, self.H, self.W)
>         tpn = tpn_maker(input_shape)
>         mod1 = ind_emb[0]
>         aligned_ind_emb = [mod1]
>         for mod in ind_emb[1:]:
>             aligned_mod = merge([tpn([mod1, mod]), mod], mode=STMerge, output_shape=input_shape)
>             aligned_ind_emb.append(aligned_mod)
>         ind_emb = aligned_ind_emb
> ```
> 
> Let's assume the input modalities are: ['T1', 'T2']. The code defines a merge layer between 'T1' and a spatial transformation of 'T1' and 'T2', let's say ST_T1_T2.
> 
> However in doing so, the final `ind_emb` does not retain the original 'T2' input. The contents of `ind_emb` should have been: ['T1', 'T2', 'ST_T1_T2'], however, the contents become: ['T1', 'ST_T1_T2']. Hence when I try to load a model with only 'T2' as input, it fails, because it cannot find the original 'T2' input.
> 
> The fix is here:
> 
> ```python
> if self.spatial_transformer:
>     print 'Adding a spatial transformer layer'
>     input_shape = (self.latent_dim, self.H, self.W)
>     tpn = tpn_maker(input_shape)
>     aligned_ind_emb = ind_emb
>     for mod in range(len(ind_emb)-1):
>         aligned_mod = merge([tpn([ind_emb[mod], ind_emb[mod+1]]), ind_emb[mod+1]], mode=STMerge, output_shape=input_shape)
>         aligned_ind_emb.append(aligned_mod)
>     ind_emb = aligned_ind_emb
> ```
> 
> `ind_emb` now contains the following: ['T1', 'T2', 'ST_T1_T2']. If I try to load a model with only 'T2' input, I can successfully do it now.
> 
> Please let me know if this is the intended use of Spatial Transformer. The paper doesn't describe the use to ST layer, so I'm in the dark.
> 
> The fix code I provide will have a different behaviour when more than two inputs are given. For instance, for inputs: ['T1', 'T2', 'T1CE'], the `ind_emb` after spatial transformer is added, will be: ['T1', 'T2', 'T1CE', 'ST_T1_T2', 'ST_T2_T1CE']. Is this how it's supposed to be?

Hi, Did you manage to get this work for more that 2 inputs? I have input_modalities = ['T1', 'T2', 'FLAIR'] and can only get partial models for inputs ['T1','T2'] and ['T1','FLAIR']. For ['T2','FLAIR'] I get

"RuntimeError: Graph disconnected: cannot obtain value for tensor /enc_T1_input at layer "enc_T1_input". The following previous layers were accessed without issue: []"

I have tried your solution but I get: "Output "em_4_dec_T1" missing from loss dictionary"

**Comment by anlarro** [comment]
@agis85 can you comment on this please?
